### ISSUE TITLE
Receiving SignatureDoesNotMatch errors after upgrading from 2.0.0

### ISSUE THREAD

**Issue by MrPetovan** [akeeba/s3#33]
We use this S3 connector over at Friendica and we recently upgraded the library from version 2.0.0 to version 2.3.1 to suppress Deprecation messages, but unfortunately [our users have been reporting errors](https://github.com/friendica/friendica/issues/13760) since.

The code using the connector didn't change, only the library was upgraded. Do you know if any changes in the library would explain this unexpected behavior?

```
Uncaught Exception Friendica\Core\Storage\Exception\StorageException: "Cannot put data for reference 6e20c847806569877e01306cd884b0be47292dbf059be105cbce272e65c95f05" at /s3_storage/src/S3Client.php line 88

Akeeba\S3\Exception\CannotPutFile: Akeeba\S3\Connector::putObject(): [500] SignatureDoesNotMatch:The request signature we calculated does not match the signature you provided. Check your key and signing method.

Debug info:
SimpleXMLElement Object
(
    [Code] => SignatureDoesNotMatch
    [Message] => The request signature we calculated does not match the signature you provided. Check your key and signing method.
    [Key] => 6e/20
    [BucketName] => 
    [Resource] => /6e/20/c847806569877e01306cd884b0be47292dbf059be105cbce272e65c95f05
    [RequestId] => 17A3F499D8B38E7E
    [HostId] => d766ec9d-ed08-47e8-bb7c-f968dbd4f006
)
 in /addon/s3_storage/vendor/akeeba/s3/src/Connector.php:149
Stack trace:
#0 /addon/s3_storage/src/S3Client.php(85): Akeeba\S3\Connector->putObject()
#1 /src/Model/Photo.php(454): Friendica\Addon\s3_storage\src\S3Client->put()
...
#18 /index.php(46): Friendica\App->runFrontend()
#19 {main}

Next Friendica\Core\Storage\Exception\StorageException: Cannot put data for reference 6e20c847806569877e01306cd884b0be47292dbf059be105cbce272e65c95f05 in /addon/s3_storage/src/S3Client.php:88
Stack trace:
#0 /src/Model/Photo.php(454): Friendica\Addon\s3_storage\src\S3Client->put()
...
#17 /index.php(46): Friendica\App->runFrontend()
#18 {main}
```

**Comment by nikosdion** [comment]
Are you using Amazon S3 proper, or a third party (non-Amazon) storage service? In the latter case, please remember that you need to explicitly set the v2 signature method and whether to use paths or subdomains.

Beyond that, version 2.3 is fully tested against Amazon S3 with actual integration tests, as you can see. You can try them from your end to make sure that you can connect to Amazon S3.

**Comment by MrPetovan** [comment]
Thank you for the answer, I'll forward it to the original issue!
